### ISSUE TITLE
INPUTSTREAM_INFO::m_flags

### ISSUE THREAD

**Issue by peak3d** [xbmc/inputstream.rtmp#27]
There is a new m_flags fiels in INPUTSTREAM_INFO to specify infos for selectionStream.
You may want to initialize it to FLAG_NONE?

https://github.com/xbmc/xbmc/pull/12690

**Comment by notspiff** [comment]
This sounds like a job for the base class.

18. aug. 2017 20:51 skrev "Markus Pfau" <notifications@github.com>:

**Comment by svenfoo** [comment]
I agree that this should be fixed in the base class. The code there leaves most instance variables uninitialized. This causes undefined behaviour unless the values are explicitly initialized later.

Will open a pull request against xbmc later...
