### ISSUE TITLE
Latest librtmp not inside the inputstream.rtmp

### ISSUE THREAD

**Issue by ozzymanborn** [xbmc/inputstream.rtmp#29]
I'm using still spmc because it had latest rtmp in their fork. But spmc based on kodi 17 not include that commit. (nor original kodi 17 versions having latest rtmp)
https://github.com/koying/SPMC/commit/248cde7beb32389cf3dcefc5a586708451d2ac91 this is really easy to apply. But it's seems not applied in inputstream.rtmp

My Original issue: https://github.com/koying/SPMC/issues/1079

@guidosarducci told me "Might be worthwhile to also raise this request at the upstream inputstream.librtmp repo."

**Comment by MartijnKaijser** [comment]
guess this is obsolete
