### ISSUE TITLE
Unable to build against openssl 1.1.0

### ISSUE THREAD

**Issue by Lou-Cipher** [xbmc/inputstream.rtmp#31]
Getting build errors, appears to be the result of changes made in openssl 1.10.  See attached log for details.

[rtmp.txt](https://github.com/notspiff/inputstream.rtmp/files/1565523/rtmp.txt)

**Comment by notspiff** [comment]
does the close mean you figured it out ?

**Comment by Lou-Cipher** [comment]
Sorry, meant to leave a comment with that.  Realized my issue might be all wrong, I'm not sure the openssl version is the issue, but it looks like the problem is building librtmp itself, figured it's an upstream issue.  What's odd is it seems to be an issue with librtmp's use of polarssl, which is now mbed-tls or some such, which I don't think it should be using anyway, since I don't have the libraries installed, figure it would go with gnutls based on the #ifdef, but after looking through the code more, it looks like it's erroring off in an #ifdef block for USE_POLARSSL.  My C is a bit rusty though, and I haven't dug much deeper (to quote Gary Larson, it was late and I was tired).

**Comment by Lou-Cipher** [comment]
OK, I'm going to reopen this.  I've done more digging, and understand the code and build process a bit better.  So, the issue is building against OpenSSL 1.1.0.  Technically, it is an upstream issue with rtmpdump not building against 1.1.0, but since rtmpdump appears to be unmaintained, and is built from a static tarball (http://mirrors.xbmc.org/build-deps/sources/rtmpdump-fa8646daeb19dfd12c181f7d19de708d623704c0.tar.gz), it would have to be forked and updated to be compatible with 1.1.0.  Probably too much work for unmaintained software.  The other two options I see are:

Allow dynamic linking with the distro's included librtmp libraries (Debian, at least, provides librtmp1 and librtmp-dev, satisfying the dependency), or

Switch to an alternate implementation, such as srs.librtmp (with which I'm completely unfamiliar other than it exists, is maintained, and is forked from the original rtmpdump).

**Comment by Lou-Cipher** [comment]
Just wanted to post a workaround for those who, like me, are running an OS with openssl 1.1.0.  This is specific to debian buster/sid, but the same concepts should apply. Note that the workaround needed to fix building librtmp is the same workaround needed to fix building kodi itself at this point.  Note too that this is a temporary workaround; at some point openssl1.0.2 will be deprecated completely, at which point Kodi and libssh will have moved on to supporting 1.1, but with no dev work on librtmp itself, this will become a showstopper for inputsream.rtmp when libssl1.0.2 is no longer available.

First, you need libssh-dev.  Which now (as of 8.x) depends on libssl-dev (interestingly, it appears the package is dependent on 1.1, but still uses the deprecated syntax of 1.0.x, but libssh-dev 8.0 is still not finalized, from the looks of things), but libssl-dev conflicts with libssl1.0-dev, which is still a dependency for KDE (my desktop of choice). Also, I had libssh2-1-dev installed as a result of the dependency update on libssh-dev, and libssh-dev has a conflict with libssh2-dev (not actually, but it's in the deb, I've submitted a bug report to the package maintainer).  As you can see, this was a fun project.  Here's how you fix this:

Ensure you have both libssl1.0.2 and libssl1.1 installed (the library packages don't conflict, just the -dev packages).  Run the following (and check your man pages if you don't understand these commands):

`apt download libssh-dev
sudo dpkg --force-conflicts --ignore-depends libssl-dev -i libssh-dev_0.8.0~20170825.94fa1e38-1_amd64.deb`

Obviously update the filename in the dpkg command with the filename you downloaded from the repo, it may get updated again soon.

Now you have libssh-dev installed, but when you try to build Kodi, you'll find it still tries to link against your libssl1.1 libraries, not the 1.0.2 it still needs.  So, you'll need to specify the full path to the ssl library in kodi's cmake configuration.  Run the following, modifying for any options you'd like to add:

`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_OPENSSL=1 -DOPENSSL_CRYPTO_LIBRARY=/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 -DOPENSSL_SSL_LIBRARY=/usr/lib/x86_64-linux-gnu/libssl.so ..
cmake --build . -- VERBOSE=1 -j4`

Now, you should be able to build your addons as usual along these lines:

`cmake -DADDONS_TO_BUILD=all -DCMAKE_INSTALL_PREFIX=/home/loucipher/repos/garbear/xbmc/addons -DPACKAGE_ZIP=1 /home/loucipher/repos/garbear/xbmc/cmake/addons/`

That allowed me to successfully build all but two addons (neither of which errored due to openssl, entirely different reasons, one was screensavers.rsxs, so when I get some time I'll check that out and open an issue about that notspiff, the other was peripheral.xarcade).

Sorry that's so longwinded, it's been quite an interesting process.  Also worth noting that before doing any of this, I merged upstream xbmc changes into the retroplayer branch, resolved a few simple conflicts, and built that (the retroplayer branch has fallen way behind master).

**Comment by notspiff** [comment]
thanks for the info. i will get around to fixing build with 1.1 before this bites.

**Comment by Lou-Cipher** [comment]
So, just a heads-up, this has officially bitten on Debian Sid, with Buster soon to follow.  The clincher was libcurl4 and libcurl4-openssl-dev, which are built against libssl 1.1, and I haven't found a way to resolve the dependency hell for this one.  Trying to force kodi to build against openssl 1.0.2 as I described above, after upgrading to libcurl4 causes all kinds of build issues, and the dependency is burried deeply enough that downgrading to libcurl3 isn't really an option. Buster is still on libcurl3, but once they update it, it will no longer be possible to build this plugin.
