### ISSUE TITLE
Android cross compile breaks with version 2.0.4 and OpenSSL 1.1.1

### ISSUE THREAD

**Issue by jairoxyz** [xbmc/inputstream.rtmp#43]
Trying to cross-compile for arm7 like I did successfully with version 2.0.3 following the guide in https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md#6-build-binary-add-ons but it breaks in OpenSSL:

`
Configuring OpenSSL version 1.1.1 (0x1010100fL) for android-arm
Using os-specific seed configuration
$ANDROID_NDK is not defined at (eval 6) line 26.
CMakeFiles/openssl.dir/build.make:105: recipe for target 'openssl-prefix/src/openssl-stamp/openssl-configure' failed
make[11]: *** [openssl-prefix/src/openssl-stamp/openssl-configure] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/openssl.dir/all' failed
make[10]: *** [CMakeFiles/openssl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
`
Is there any additional requirement now for x-compiling the addon? I exported ANDROID_NDK but no change. Kodi itself compiles fine though.

Thanks.

**Comment by Rechi** [comment]
What exact (git ref) Kodi source are you using?

**Comment by jairoxyz** [comment]
Hi, I cloned into https://github.com/xbmc/xbmc/tree/18.0b4-Leia

**Comment by lorkadiscovery** [comment]
Hello, I also get the same error on Ubuntu 16.04.5 when compiling for arm v8a.

`make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons ADDONS="inputstream.rtmp"`

`Scanning dependencies of target openssl
make[7]: Leaving directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/openssl/src/openssl-build'
make[7]: Entering directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/openssl/src/openssl-build'
[ 12%] Creating directories for 'openssl'
[ 25%] No download step for 'openssl'
[ 37%] No patch step for 'openssl'
[ 50%] No update step for 'openssl'
-- Looking for pthread.h - found
-- Looking for pthread_create
[ 62%] Performing configure step for 'openssl'
Configuring OpenSSL version 1.1.1 (0x1010100fL) for android-arm64
Using os-specific seed configuration
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Performing Test HAS_BUILTIN_SYNC_ADD_AND_FETCH
$ANDROID_NDK is not defined at (eval 6) line 26.
CMakeFiles/openssl.dir/build.make:105: recipe for target 'openssl-prefix/src/openssl-stamp/openssl-configure' failed
make[7]: *** [openssl-prefix/src/openssl-stamp/openssl-configure] Error 2
make[7]: Leaving directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/openssl/src/openssl-build'
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/openssl.dir/all' failed
make[6]: *** [CMakeFiles/openssl.dir/all] Error 2
make[6]: Leaving directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/openssl/src/openssl-build'
Makefile:129: recipe for target 'all' failed
make[5]: *** [all] Error 2
make[5]: Leaving directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug/build/openssl/src/openssl-build'
CMakeFiles/openssl.dir/build.make:113: recipe for target 'build/openssl/src/openssl-stamp/openssl-build' failed
make[4]: *** [build/openssl/src/openssl-stamp/openssl-build] Error 2
make[4]: Leaving directory '/home/lorka/beta_4/tools/depends/target/binary-addons/aarch64-linux-android-21-debug'
CMakeFiles/Makefile2:240: recipe for target 'CMakeFiles/openssl.dir/all' failed
make[3]: *** [CMakeFiles/openssl.dir/all] Error 2`

**Comment by wsnipex** [comment]
beta4 lacks https://github.com/xbmc/xbmc/commit/4ac4445d0073a34a5363281f047b329fb7852c37 which should fix the issue

**Comment by jairoxyz** [comment]
Thanks! Will try.

**Comment by jairoxyz** [comment]
xbmc/xbmc@4ac4445 solves the problem. thanks to all.
